site_name: obsidian-workflow-template-docs
repo_url: https://github.com/mathisgauthey/obsidian-workflow-template
repo_name: mathisgauthey/obsidian-workflow-template-docs
markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - footnotes
  - toc:
      permalink: true
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.tabs.sticky
nav:
  - Home: index.md
  - Getting Started:
    - Why should you use this template?: getting-started/why-should-you-use-this-template.md
    - Requirements: getting-started/requirements.md
    - Installation: getting-started/installation.md
    - File Structure: getting-started/file-structure.md
    - Usage: getting-started/usage.md
