site_name: obsidian-workflow-template-docs
repo_url: https://github.com/mathisgauthey/obsidian-workflow-template
repo_name: mathisgauthey/obsidian-workflow-template-docs
markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - footnotes
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
nav:
  - Home: index.md
  - Getting Started:
    - Why should you use this template?: getting-started/why-should-you-use-this-template.md
    - Requirements: getting-started/requirements.md
    - Installation: getting-started/installation.md
    - File Structure: getting-started/file-structure.md
    - Auto-upload to website: getting-started/auto-upload-to-website.md
  - Usage:
    - Tasks and projects creation: usage/tasks-and-projects-creation.md
    - Tasks and projects management: usage/tasks-and-projects-management.md
    - Journaling: usage/journaling.md
    - Passions backlog: usage/passions-backlog.md
    - Read-it-later: usage/read-it-later.md
    - Github-publisher: usage/github-publisher.md
    - Template files: usage/template-files.md